#!/usr/bin/env python3
"""Train B-Spline Policy on a converted recording.

    python -m baselines.bspline_bridge.train ~/franka_data/baseline_prep/<dataset>/bspline.hdf5

Upstream trains through hydra with a task config that names the observation
keys, their shapes and the HDF5 (baselines/BSPLINE_POLICY.md). Its shipped task
describes their arm and camera, so one is generated here from the file --
which is also the only safe source for the image shape: the replay conversion
copies frames into a zarr of exactly `shape_meta`'s shape and fails otherwise.

The generated task goes into the run directory and reaches hydra through
--config-dir, so nothing is written into the submodule; hydra.run.dir moves
the outputs out of the checkout to <output-dir>/<name>/<timestamp>/, whose
checkpoints/latest.ckpt is what bspline_rollout.sh --ckpt takes.

--resume <run_dir> continues one of those from its checkpoints/latest.ckpt
(model, EMA, optimizer, epoch and step) to the epoch count it was started with;
bspline_train.py explains what upstream's own resume gets wrong.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT))

import h5py  # noqa: E402

from baselines.interpreters import python_for  # noqa: E402
from baselines.train_common import crop_size, policies_dir, stream  # noqa: E402

logger = logging.getLogger("baselines.bspline.train")

PROJECT = _REPO_ROOT / "baselines" / "bspline_policy" / "bspline_policy"
UPSTREAM_TRAIN = PROJECT / "train.py"
TRAIN_SCRIPT = Path(__file__).resolve().parent / "bspline_train.py"
PROBE_SCRIPT = Path(__file__).resolve().parent / "dataset_len.py"
WORKSPACE_CONFIG = "train_diffusion_unet_real_hybrid_bspline_workspace"
TASK_NAME = "franka_bspline"
# The loader turns our 7-dim [pos, rotvec, gripper] rows into rotation_6d.
RAW_ACTION_DIM, MODEL_ACTION_DIM = 7, 10


@dataclass
class Info:
    path: Path
    source_repo_id: str | None
    demos: int
    obs_shapes: dict[str, tuple[int, ...]]   # key -> per-step shape, as stored
    action_dim: int


def inspect_hdf5(path: Path) -> Info:
    with h5py.File(path, "r") as f:
        repo_id = f.attrs.get("source_repo_id")
        if isinstance(repo_id, bytes):
            repo_id = repo_id.decode()
        demos = list(f["data"].keys())
        if not demos:
            raise SystemExit(f"{path} holds no demos")
        first = f["data"][demos[0]]
        obs = {k: tuple(int(x) for x in v.shape[1:]) for k, v in first["obs"].items()}
        action_dim = int(first["actions"].shape[1])
    return Info(path, str(repo_id) if repo_id else None, len(demos), obs, action_dim)


def shape_meta(info: Info) -> dict:
    obs = {}
    for key, shape in sorted(info.obs_shapes.items()):
        if key.endswith("_image"):
            if len(shape) != 3 or shape[2] != 3:
                raise SystemExit(f"{key} is {shape}, expected (H, W, 3) uint8")
            h, w, c = shape
            obs[key] = {"shape": [c, h, w], "type": "rgb"}
        else:
            obs[key] = {"shape": list(shape)}
    return {"obs": obs, "action": {"shape": [MODEL_ACTION_DIM]}}


# wandb caps a tag at 64 characters and RAISES on a longer one (a pydantic
# ValidationError out of wandb.init), so an over-long name fails the training
# run minutes in rather than warning. Upstream tags every run with
# `${task_name}`, which is the `name:` below.
WANDB_TAG_MAX = 64


def task_name(dataset: Path) -> str:
    """`<dataset directory>-bspline`, short enough to be a wandb tag.

    A long name keeps a readable prefix plus a hash of the whole thing: LIBERO
    task directories differ at the END (`..._on_the_plate` vs
    `..._on_the_left_plate`), so plain truncation would collide and two tasks
    would log to one tag.
    """
    name = f"{dataset.parent.name}-bspline"
    if len(name) <= WANDB_TAG_MAX:
        return name
    digest = hashlib.sha1(name.encode()).hexdigest()[:8]
    return f"{name[:WANDB_TAG_MAX - len(digest) - 1]}-{digest}"


def task_yaml(info: Info, meta: dict) -> str:
    st = info.path.stat()
    # YAML is a JSON superset, so the shape block can be emitted verbatim.
    return f"""# Generated by baselines/bspline_bridge/train.py from {info.path}
name: {task_name(Path(info.path))}

shape_meta: &shape_meta {json.dumps(meta)}

dataset_path: &dataset_path {info.path.resolve()}
abs_action: &abs_action True

# A no-op runner: there is no simulator for this task, evaluation is a rollout
# on the arm (baselines/ROLLOUT.md).
env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: bspline_policy.dataset.robomimic_replay_bspline_image_dataset.RobomimicReplayBSplineImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${{horizon}}
  pad_before: 0
  pad_after: 0
  n_obs_steps: ${{dataset_obs_steps}}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  bspline_degree: 3
  chunk_size: ${{eval:'${{horizon}}-2*${{task.dataset.bspline_degree}}'}}
  max_error: 0.002
  stride: 1
  relative_knots: false
  use_cache: True
  # Keyed by size and mtime: the zarr cache next to the HDF5 is otherwise only
  # keyed by this suffix, and a regenerated file would silently reuse it.
  cache_suffix: franka_{st.st_size}_{int(st.st_mtime)}
  seed: 42
  val_ratio: 0.0
"""


def epochs_for_steps(steps: int, python: list[str], hydra_dir: Path, overrides: list[str],
                     env: dict) -> int:
    """Epochs that give at least `steps` gradient steps, with the last one saved.

    The epoch length is measured by building the dataset (dataset_len.py) under
    the same config the trainer gets; the result is rounded up to k*checkpoint_every+1
    because the workspace only writes latest.ckpt on epochs divisible by
    checkpoint_every, so any other count ends on an unsaved epoch.
    """
    probe_overrides = [o for o in overrides if not o.startswith("hydra.run.dir=")]
    probe_overrides.append(f"hydra.run.dir={hydra_dir / 'probe'}")
    cmd = [*python, str(PROBE_SCRIPT), "--config-dir", str(hydra_dir),
           "--config-name", WORKSPACE_CONFIG, *probe_overrides]
    logger.info("measuring an epoch: $ cd %s && %s", PROJECT, " ".join(cmd))
    proc = subprocess.run(cmd, cwd=str(PROJECT), env=env, text=True,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    line = next((ln for ln in reversed(proc.stdout.splitlines()) if ln.startswith("{")), None)
    if proc.returncode != 0 or line is None:
        raise SystemExit(f"dataset_len.py failed (exit {proc.returncode}):\n{proc.stdout[-3000:]}")
    probe = json.loads(line)
    samples, batch = int(probe["samples"]), int(probe["batch_size"])
    per_epoch = -(-samples // batch)                      # DataLoader keeps the last partial batch
    checkpoint_every = int(probe["checkpoint_every"])
    needed = -(-int(steps) // per_epoch)
    k = -(-(needed - 1) // checkpoint_every)
    epochs = k * checkpoint_every + 1
    logger.info("--steps %d: %d samples / batch %d = %d steps per epoch -> %d epochs "
                "(%d steps; %d needed, rounded to k*%d+1 so the last epoch checkpoints)",
                steps, samples, batch, per_epoch, epochs, epochs * per_epoch, needed,
                checkpoint_every)
    return epochs


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("hdf5", type=Path, help="bspline.hdf5 from scripts/prepare_baseline_datasets.py")
    p.add_argument("--output-dir", type=Path, default=None,
                   help="default ~/franka_data/policies/<train-dataset>")
    p.add_argument("--name", default="bspline", help="a subdirectory of --output-dir")
    p.add_argument("--resume", type=Path, default=None, metavar="RUN_DIR",
                   help="continue this earlier run (<output-dir>/<name>/<timestamp>) from its "
                        "checkpoints/latest.ckpt; --epochs/--steps then come from the checkpoint")
    p.add_argument("--epochs", type=int, default=None, help="default: the workspace config's (601)")
    p.add_argument("--steps", type=int, default=None,
                   help="gradient-step budget in place of --epochs, the count lerobot-train's "
                        "--steps means: the dataset is built once to measure an epoch "
                        "(dataset_len.py) and epochs = ceil(steps / steps_per_epoch), rounded "
                        "up to the next k*checkpoint_every + 1 so the last epoch is saved")
    p.add_argument("--checkpoint-every", type=int, default=None, help="default: the config's (100)")
    p.add_argument("--batch-size", type=int, default=None)
    p.add_argument("--num-workers", type=int, default=None, help="dataloader workers")
    p.add_argument("--seed", type=int, default=None)
    p.add_argument("--device", default=None, help="e.g. cuda:0")
    p.add_argument("--wandb", action="store_true", help="log online; default offline")
    p.add_argument("--wandb-project", default=None, help="default: the workspace config's")
    p.add_argument("--wandb-name", default=None, help="run name on wandb; default: the workspace's")
    p.add_argument("--dry-run", action="store_true",
                   help="print the generated task and the command, run nothing")
    p.add_argument("--python", default=None, help="interpreter of the B-Spline env; default: resolved")
    args = p.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    if args.steps is not None and args.epochs is not None:
        p.error("--steps and --epochs are two ways to say the same thing; pass one")
    if not args.hdf5.is_file():
        p.error(f"{args.hdf5} does not exist")
    if not UPSTREAM_TRAIN.is_file():
        p.error(f"{UPSTREAM_TRAIN} is missing; git submodule update --init baselines/bspline_policy")
    if args.resume is not None:
        if not (args.resume / "checkpoints" / "latest.ckpt").is_file():
            p.error(f"{args.resume} has no checkpoints/latest.ckpt to resume from")
        if args.steps is not None or args.epochs is not None:
            logger.warning("--resume: the epoch count comes from the checkpoint; --steps/--epochs ignored")
            args.steps = args.epochs = None

    info = inspect_hdf5(args.hdf5)
    if info.action_dim != RAW_ACTION_DIM:
        p.error(f"actions are {info.action_dim}-dim, expected {RAW_ACTION_DIM} "
                "(pos + rotvec + gripper); this is not a B-Spline conversion")
    meta = shape_meta(info)
    images = [k for k, v in meta["obs"].items() if v.get("type") == "rgb"]
    if not images:
        p.error("no camera keys in the file; convert without --no-images")
    _, h, w = meta["obs"][images[0]]["shape"]
    logger.info("dataset %s: %d demos, cameras %s at %dx%d, trained on %r",
                args.hdf5, info.demos, images, h, w, info.source_repo_id)

    output_dir = policies_dir(info.source_repo_id, args.output_dir)
    if args.resume is not None:
        run_dir = args.resume.resolve()
    else:
        run_dir = output_dir / args.name / time.strftime("%Y%m%d_%H%M%S")
    hydra_dir = run_dir / "hydra"
    task_text = task_yaml(info, meta)

    python = [args.python] if args.python else python_for("bspline")
    # On a resume the launcher sets the run dir, training.resume and the epoch count.
    resume = ["--resume", str(run_dir)] if args.resume is not None else []
    overrides = [
        f"task={TASK_NAME}",
        *([] if resume else [f"hydra.run.dir={run_dir}", f"multi_run.run_dir={run_dir}",
                             "training.resume=false"]),
        f"logging.mode={'online' if args.wandb else 'offline'}",
        f"policy.crop_shape=[{crop_size(h, w)[0]},{crop_size(h, w)[1]}]",
    ]
    for flag, key in (("epochs", "training.num_epochs"),
                      ("checkpoint_every", "training.checkpoint_every"),
                      ("seed", "training.seed"),
                      ("device", "training.device"),
                      ("wandb_project", "logging.project"),
                      ("wandb_name", "logging.name")):
        if getattr(args, flag) is not None:
            overrides.append(f"{key}={getattr(args, flag)}")
    if args.batch_size is not None:
        overrides += [f"dataloader.batch_size={args.batch_size}",
                      f"val_dataloader.batch_size={args.batch_size}"]
    if args.num_workers is not None:
        overrides += [f"dataloader.num_workers={args.num_workers}",
                      f"val_dataloader.num_workers={args.num_workers}"]
    env = {**os.environ, "HYDRA_FULL_ERROR": "1",
           "WANDB_MODE": "online" if args.wandb else "offline"}

    if args.dry_run:
        logger.info("[dry-run] %s/task/%s.yaml:\n%s", hydra_dir, TASK_NAME, task_text)
        if args.steps is not None:
            logger.info("[dry-run] --steps %d: epochs are resolved at launch by building the "
                        "dataset (dataset_len.py)", args.steps)
        cmd = [*python, str(TRAIN_SCRIPT), *resume, "--config-dir", str(hydra_dir),
               "--config-name", WORKSPACE_CONFIG, *overrides]
        logger.info("[dry-run] cd %s && %s", PROJECT, " ".join(cmd))
        return 0

    (hydra_dir / "task").mkdir(parents=True, exist_ok=True)
    (hydra_dir / "task" / f"{TASK_NAME}.yaml").write_text(task_text)
    if args.steps is not None:
        epochs = epochs_for_steps(args.steps, python, hydra_dir, overrides, env)
        overrides.append(f"training.num_epochs={epochs}")
    cmd = [*python, str(TRAIN_SCRIPT), *resume, "--config-dir", str(hydra_dir),
           "--config-name", WORKSPACE_CONFIG, *overrides]
    logger.info("%s %s", "resuming" if resume else "run directory", run_dir)
    t0 = time.time()
    rc, _ = stream(cmd, PROJECT, env=env)
    ckpt = run_dir / "checkpoints" / "latest.ckpt"
    if rc != 0 or not ckpt.is_file() or ckpt.stat().st_mtime < t0:
        logger.error("training failed (exit %d); no new %s", rc, ckpt)
        return rc or 1
    logger.info("trained in %.0fs; checkpoint:\n  %s", time.time() - t0, ckpt)
    logger.info("roll it out with:\n  ./scripts/bspline_rollout.sh --start-server --ckpt %s "
                "--rig=single_arm_right --speed-up-times 1.0", ckpt)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
