#!/usr/bin/env bash
# Deploy the pylibfranka torque server to a NUC and restart it.
#
# The server and the OSC controller are copied flat into ~/ on the NUC so the
# server's `from osc_torque_controller import ...` fallback resolves without a
# package install. Restarting kills whatever is bound to the port first --
# including the old net_franky `rpyc_classic` server, which cannot coexist with
# this one on that port.
#
# The NUC env is numpy + pylibfranka only, so franka_config is not importable
# there. config/control.yaml's `torque:` block is therefore resolved HERE and
# written out as nuc_control_config.py, which torque_config.py picks up on the
# NUC. That keeps control.yaml authoritative on both sides -- but it also means
# a gain change only reaches the arm once you re-run this script.
#
# Hosts and ports come from config/arms.yaml via `python -m franka_config arm`.
#
# Usage: deploy_nuc_server.sh [mario|luigi] [--no-restart]
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/_config.sh"

TARGET="${1:-mario}"
RESTART=1
[[ "${2:-}" == "--no-restart" ]] && RESTART=0

# arms.yaml keys arms by side; the NUC hostname is the deploy target's identity.
ARM=""
for side in left right; do
  if [[ "$(cfg "arms.arms.${side}.nuc_host")" == "$TARGET" ]]; then ARM="$side"; break; fi
done
[[ -n "$ARM" ]] || { echo "unknown target '$TARGET': no arm in config/arms.yaml has nuc_host = $TARGET" >&2; exit 1; }

eval "$(cfg_arm "$ARM" --prefix A)"
HOST="$A_SSH"; PORT="$A_PORT"; GRIPPER_PORT="$A_GRIPPER_PORT"
echo "==> $TARGET is the $ARM arm: $HOST port $PORT (gripper $GRIPPER_PORT)"

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lerobot_robot_bimanual_franka/lerobot_robot_bimanual_franka"

echo "==> resolving config/control.yaml torque block"
GENERATED="$(mktemp -t nuc_control_config.XXXXXX.py)"
trap 'rm -f "$GENERATED"' EXIT
# repr(), not JSON: JSON's true/false/null are not Python literals, so a bool
# added to the torque block later would emit a file that fails to import on the
# NUC -- after the arm is already running on the old one.
python - "$GENERATED" <<'PY'
import sys
import franka_config as fc

with open(sys.argv[1], "w", encoding="utf-8") as fh:
    fh.write(
        '"""GENERATED by scripts/deploy_nuc_server.sh -- do not edit.\n\n'
        "The `torque:` block of config/control.yaml, resolved on the workstation\n"
        "because the NUC has no franka_config. Read it through torque_config.py.\n"
        "Re-run the deploy script to pick up a control.yaml change.\n"
        '"""\n\nTORQUE = ' + repr(fc.control("torque")) + "\n"
    )
PY
python -c "import ast,sys; ast.parse(open(sys.argv[1]).read())" "$GENERATED"

echo "==> copying server to $HOST"
scp -q "$SRC/pylibfranka_server.py" "$SRC/pylibfranka_control.py" "$SRC/pylibfranka_shm.py" \
    "$SRC/osc_torque_controller.py" "$SRC/franka_jacobian.py" "$SRC/torque_config.py" \
    "$HOST:~/"
scp -q "$GENERATED" "$HOST:~/nuc_control_config.py"

echo "==> writing run_server.sh"
ssh "$HOST" "cat > ~/run_server.sh" <<EOF
#!/usr/bin/env bash
# pylibfranka RPyC torque server for the FR3 1 kHz control loop.
#
# SCHED_FIFO prio 80 (chrt -f) so the libfranka realtime thread outranks normal
# nice-0 kernel workers -- without it the loop runs at the inherited nice and the
# OS preempts it past the 1 kHz deadline -> "UDP receive: Timeout". taskset keeps
# it off CPU0/1 where ACPI/PM kworkers cluster. (User must be in @realtime.)
#
# Unlike the old net_franky launcher this runs our own module rather than the
# generic rpyc_classic entrypoint: the torque loop has to live inside the
# process that holds the ActiveControlBase.
#
# The gripper runs in a SEPARATE process on its own port. pylibfranka's Gripper
# bindings hold the GIL across blocking calls -- measured 100 ms of stall for a
# single read_once -- which inside this process would freeze the 1 kHz RT thread
# and abort the motion with communication_constraints_violation. A separate
# process means a separate GIL. It is left at normal priority on CPU 0-1 so it
# cannot compete with the realtime thread either.
source ~/pylibfranka_env/bin/activate
taskset -c 0-1 rpyc_classic -p $GRIPPER_PORT --host 0.0.0.0 >~/gripper_server.log 2>&1 &
# The server is a shared-memory proxy with no control loop in it, so it runs at
# normal priority -- but it must still be kept OFF cores 2-7. SCHED_FIFO 80 only
# beats it for CPU; it does not stop RPyC's socket work from evicting the RT
# loop's cache or piling NET_RX softirqs onto the loop's cores. Measured: with
# the server free to roam 0-7, 30 Hz of get_state drove the loop's own compute
# from 345 us to 765 us and started a cascade of communication_constraints_
# violation aborts. Same reason the gripper is pinned here.
exec taskset -c 0-1 python ~/pylibfranka_server.py --port $PORT --host 0.0.0.0
EOF
ssh "$HOST" "chmod +x ~/run_server.sh"

echo "==> import check"
ssh "$HOST" "source ~/pylibfranka_env/bin/activate && python3 -c '
import ast, sys
for f in (\"pylibfranka_server.py\", \"pylibfranka_control.py\", \"pylibfranka_shm.py\", \"osc_torque_controller.py\", \"franka_jacobian.py\", \"torque_config.py\", \"nuc_control_config.py\"):
    ast.parse(open(f).read())
import pylibfranka, rpyc, numpy
print(\"pylibfranka\", pylibfranka.__version__ if hasattr(pylibfranka, \"__version__\") else \"ok\", \"rpyc\", rpyc.__version__)
import osc_torque_controller, franka_jacobian, pylibfranka_shm
# Importing these proves the generated config resolved: torque_config raises
# rather than falling back to a stale gain, so a bad deploy fails HERE and not
# mid-trajectory on the arm.
print(\"osc_torque_controller ok: kp\", osc_torque_controller.DEFAULT_KP,
      \"tau\", osc_torque_controller.JOINT_TORQUE_LIMITS)
'"

if [[ "$RESTART" == "1" ]]; then
  # Bracketed first char so the pattern never matches the shell running pkill --
  # 'rpyc_classic -p 18812' appears verbatim in that shell's own argv, so an
  # unbracketed -f pattern makes pkill kill itself before it kills the server.
  echo "==> stopping anything on port $PORT"
  ssh "$HOST" "pkill -f '[r]pyc_classic -p $PORT' || true; pkill -f '[r]pyc_classic -p $GRIPPER_PORT' || true; pkill -f '[p]ylibfranka_server.py --port $PORT' || true; pkill -f '[p]ylibfranka_control.py' || true; sleep 1"
  # The redirect binds to the subshell, not to run_server.sh: bash forks a
  # subshell for the backgrounded compound, and that subshell inheriting ssh's
  # stdout keeps the channel open, so ssh never returns even though the daemon
  # itself is fully detached.
  echo "==> starting server"
  ssh -n "$HOST" "(cd ~ && setsid ./run_server.sh) </dev/null >~/pylibfranka_server.log 2>&1 &"
  sleep 3
  ssh -n "$HOST" "tail -5 ~/pylibfranka_server.log; pgrep -af '[p]ylibfranka_server.py' || { echo 'SERVER NOT RUNNING' >&2; exit 1; }"
  ssh -n "$HOST" "pgrep -af '[r]pyc_classic -p $GRIPPER_PORT' || { echo 'GRIPPER SERVER NOT RUNNING' >&2; exit 1; }"
fi

echo "==> done ($TARGET)"
